tempdir:                     "/tmp/"
reference:                   "data/refgen/GRCh37/Homo_sapiens.GRCh37.dna.primary_assembly.fa"

# ---- Netrules configuration.
netrules:
  retries:                   20
  refgen:                    "ftp.ensembl.org/pub/grch37/current/fasta/homo_sapiens/dna/"
  TKGWV2:
    support-files-url:       "https://drive.google.com/drive/folders/1Aw-0v_7CUorHJOLpCJ0QVCwEdH43HlO4"
    support-files-dir:       "data/TKGWV2"

# ---- BAM pre-processing and QC parameters.
preprocess:
  trimming:
    min-overlap:             1                 # 1   Minimum allowed read-mate overlap.
    min-length:              17                # 30  Minimum allowed read length
    min-quality:             20                # 20  Minimum allowed base quality
    qualitymax:              41                # 41  set to 93 if you intend to increase gargammel -qs | -qs2 parameters
    seed:                    ~                 # Random seed if empty (~)
  bwa:
    aligner:                 "aln"             # 'mem' || 'aln'
    collapsed-only:          False
    bwa-aln:
      seed-length:           1024              # 1024 (Oliva et al. 2021)
      max-open-gap:          2                 # 2    (Oliva et al. 2021)
      max-seed-diff:         2                 # 2
      max-miss-prob:         0.01              # 0.01 (Oliva et al. 2021)  
  filter:
    min-MQ:                  20
    min-length:              30
  dedup:
    method: picard                             # "samtools" | "picard" | "dedup"
  pmd-rescaling:
    rescaler: ~                        # "mapdamage" | "pmdtools" | None ('~') to skip rescale
    apply-masking: True
    map-damage:
      downsample:            ~                 # No downsampling if empty (0 < downsample < 1)
      downsample-seed:       ~                 # Random seed if empty (~)
    pmdtools:
      threshold:             -19999            # in LOD. Recommended: 3 | set to -19999 to disable
      mask-terminal-deams:   0                 # in bases. Default 0 
    pmd-mask:
      threshold: 0.01

# ---- Variant calling parameters 
variant-calling:
  targets:                   "data/Reich-dataset/1240K/v52.2/v52.2_1240K_public.snp"
  caller:                    "pileupCaller"    # ANGSD || pileupCaller
  pileup:
    disable-BAQ:             True              # True || False
    min-BQ:                  25
    min-MQ:                  25
  pileupCaller:
    skip-transitions:        False             # True || False
    mode:                    "randomHaploid"   # "randomHaploid" || "majorityCall"
    sample-pop-name:         "Cerny"
    min-depth:               1
    seed:                    ~                 # Random seed if empty

# ---- Paramaters relating to merging our samples w/ Reich 1240K compendium.
reich-merge:
  version: 52.2
  plink:
    seed:                    ~                 # Random seed if empty

# ---- Genetic relatedness estimation methods parameters.
kinship:
  READ:
    window-size:             1000000
    norm-method:             "median"          # median || mean || max || value
    norm-value:              ~                 # (Float). Ignored if norm-method != "value"
    maf:                     0.05              # (Float). Ignored if set to None (~) Requires caller='pileupCaller' and add-proxies="Reich". 
    add-proxies:             "Reich"           # "Reich" || None (~)
    proxies:                                   # Provide a list of proxy individuals to fetch from Reich' compendium. Requires caller='pileupCaller' and add-proxies='Reich'
      - GRG003
      - GRG008
      - GRG015
      - GRG016
      - GRG018
      - GRG019
      - GRG021
      - GRG022
      - GRG023
      - GRG025
      - GRG027
      - GRG028
      - GRG032
      - GRG035
      - GRG041
      - GRG043
      - GRG047
      - GRG049
      - GRG050
      - GRG052
      - GRG056
      - GRG057
      - FLR001
      - FLR002
      - FLR003
      - FLR004
      - FLR005
      - FLR007
      - FLR010
      - FLR013
      - FLR014
  GRUPS:
    pedigree:                "workflow/scripts/grups/resources/pedigrees/siblings-pedigree.txt"
    pedigree-pop:            "EUR"
    contam-pop:              "AFR"
    min-depth:               1
    mode:                    "fst"
    reps:                    1000
    maf:                     0.0
    min-qual:                25
    seq-error-rate:          0.0               # Uses pileup quality scores if empty (~)
    seed:                    ~                 # Random seed if empty (~)
  TKGWV2:
    downsample:              True             # True || False
    downsample-N:            57600000
    downsample-seed:         ~                 # Random seed if empty (~)
    #target-frequencies:      "data/TKGWV2/genomeWideVariants_hg19/1000GP3_EUR_22M_noFixed.frq"
    target-frequencies:      "data/TKGWV2/1240K/1000GP3_EUR_1240K.frq"
    min-BQ:                  25
    min-MQ:                  25
    min-depth:               1
  KIN:
    interval:                10000000
    p0-threshold:            10
    roh-threshold:           ~                # (ignored if None)
    diversity-parameter:     ~                # (ignored if None)
    noisy-windows:           ~                # (ignored if None)