
reference-genome: "GRCh37"  # ---- Reference genome used throughout the workflow.
                            #      <str> ["GRCh37" | "hs37d5" | "human_g1k_v37"]

# ---- Quality-control + statistics parameters
quality-control:
  mosdepth:               # -- Mostdepth parameter
    per-base-depth: True  #    <bool> [True | False]

# ---- FASTQ alignment and BAM pre-processing and QC parameters.
preprocess:
  trimming:                   # -------- AdapterRemoval parameters
    min-overlap:  1           # -- Minimum allowed read-mate overlap
                              #    <int> (Default: 1)
                              #
    min-length:  17           # -- Minimum allowed read length
                              #    <int> (Default: 30)
                              #     
    min-quality: 20           # -- Minimum allowed base quality
                              #    <int> (Default: 20)
                              # 
    qualitymax:  41           # -- Maximum allowed base quality (in PHRED scale)
                              #    <int> (Default: 41)
                              #
    seed:         ~           # -- AdapterRemoval RNG seed. Randomly selected if set to None (~)
                              # -- <int> (Default: ~)
                              #
  bwa:                        # -------- Burrows-Wheeler Aligner parameters
    aligner:        "aln"     # -- Main BWA module used 
                              #    <str> ["aln" | "mem"]
                              # 
    collapsed-only: False     # -- For paired-end data: whether or not non-collapsed read should be kept
                              #    <bool> [ True | False ]
    bwa-aln:                  # -------- Main parameters for bwa aln program (ignored when aligner="mem") 
      seed-length:   1024     # <int> (Default: 1024) (Oliva et al. 2021)
      max-open-gap:     2     # <int> (Default: 2)
      max-seed-diff:    2     # <int> (Default: 2)
      max-miss-prob: 0.01     # <int> (Default: 0.01)
                              #
  filter:                     # -------- Samtools pre-merge filtration parameters 
                              #
    min-MQ:     25            # -- Minimum mapping quality threshold
                              #    <int> (Default: 25)
                              #
    min-length: 30            # -- Minimum read length threshold
                              #    <int> (Default: 30)
                              #
  dedup:                      # ---- Optical PCR Duplicates removal parameters 
                              # 
    method: picard            # -- Main selected program
                              # <str> ["picard" | "samtools" | "dedup"]
                              #
  pmd-rescaling:              # -------- Post-Mortem Damage estimation and rescaling parameters 
                              #
    rescaler:      ~          # -- Main selected PMD rescaling method
                              #    Setting this parameter to None (~) will skip BAM rescaling alltogether
                              #    <str> ["mapdamage" | "pmdtools" | ~ ]
                              #
    apply-masking: True       # -- Apply selective masking using pmd-mask (https://github.com/MaelLefeuvre/pmd-mask)
                              #    <bool> [ True | False ]
                              #
    map-damage:               # -- MapDamage-v2 parameters
      downsample:      ~      #    No downsampling if empty (0 < downsample < 1)  
      downsample-seed: ~      #    RNG Seed using during downsampling. Random seed if empty (~)
                              #
    pmdtools:                 # -- PMD-tools parameters 
      threshold:      -19999  # <str>. LOD-score threshold (Recommended: 3. Set to -19999 to disable)
      mask-terminal-deams: 0  # <bp> (Default: 0)
                              # 
    pmd-mask:                 # -- pmd-mask parameters
      threshold: 0.01         #    Misincorporation rate threshold

# ---- Variant calling parameters 
variant-calling:
  caller:          "pileupCaller"       # -- Main selected random pseudo-haploid variant calling program
                                        #    <str> ["pileupCaller" | "ANGSD"]
                                        #
  sample-pop-name: "test-population"    # -- Population name identifier for the input samples.
  targets:
    custom-file:  ~                     # -- Custom path leading to an SNP targets file (EIGENSTRAT .snp) format.
                                        #    Used by samtools mpileup and sequenceTools pileupCaller. If set to
                                        #    None, will automatically download Reich Lab's AADR "1240K" dataset,
                                        #    using the provided version tag (see 'aadr-version').
                                        #    <path> (Default: None (~))
                                        #
    aadr-version: 52.2                  # -- ReichLab's AADR dataset version.
                                        #    See: https://doi.org/10.7910/DVN/FFIDCW for additional information
                                        #    <version> (<major>.<minor>) (Default: 52.2)
                                        #
  pileup:                               # -- Samtools mpileup parameters  
    disable-BAQ:  True                  #   <bool> [True | False]
    min-BQ:        25                   #   <int>
    min-MQ:        25                   #   <int>
                                        #
  pileupCaller:                         # -- SequenceTools PileupCaller parameters
    skip-transitions:  False            #   <bool> [True | False]
    mode:              "randomHaploid"  #   <str> ["randomHaploid" | "majorityCall"]
    min-depth:         1                #   <int> (Default: 1)
    seed:              ~                #   <int> (Default: ~) (Random seed if None)
                                        #
  plink:                                # -- PLINK-1.9 parameters 
    seed:              ~                #   <int> (Default: ~) (Random seed if None)

# ---- Genetic relatedness estimation methods parameters.
kinship:
  READ:                                        # ----- READ parameters  
    coverage-threshold:  10000                 # -- minimum number of non missing SNP targets required to include a
                                               #    given sample within the analysis .
                                               #    [<int> or "coverage"] (e.g.: 10000, "0.01X") 
                                               #    -> integer values are interpreted as # of covered positions
                                               #    -> suffix your value with 'X' to interpret it as coverage.
                                               #    
    window-size:         1000000               # -- Default size of non-overlapping windows for the estimation of P0 
                                               #    <int> (in base pairs) (Default: 1e6)
                                               #
    norm-method:         "median"              # -- READ Normalization method 
                                               #    <str> [ median | mean | max | value ]
                                               #
    norm-value:          ~                     # -- Normalization value (Float). Ignored if norm-method != "value"
                                               #    <float> (Default: None)
                                               #
    maf:                 0.05                  # -- Minor allele frequency filtration treshold (Float).
                                               #    - Ignored if set to None (~)
                                               #    - Requires caller="pileupCaller" and add-proxies="Reich". 
                                               #    <float> (Default: 0.05)
                                               #
    add-proxies:         "Reich"               # -- Include additional 'proxy' individuals from the AADR 1240K dataset
                                               #    within the input PLINK fileset. 
                                               #    <str> [ "Reich" | None (~) ]
                                               #
    proxies:                                   # -- Specify the sample-ids to fetch from the AADR dataset when
                                               #    adding proxy individuals. Requires caller="pileupCaller" and 
                                               #    add-proxies='Reich'
                                               #    [<str>]
      - HG00096.SG
      - HG00097.SG
      - HG00099.SG
      - HG00100.SG
      - HG00101.SG
      - HG00102.SG
      - HG00103.SG
      - HG00105.SG
  READv2:                                      # ---- READv2 parameters
    coverage-threshold: 10000                  # -- minimum number of non missing SNP targets required to include a
                                               #    given sample within the analysis .
                                               #    [<int> or "coverage"] (e.g.: 10000, "0.01X") 
                                               #    -> integer values are interpreted as # of covered positions
                                               #    -> suffix your value with 'X' to interpret it as coverage.
                                               #
    window-est:         False                  # -- Toggle legacy window-based estimate of P0. 
                                               #    <bool> [True|False] (Default: False)
                                               #
    window-size:        1000000                # -- Default size of non-overlapping windows for the estimation of P0 
                                               #    <int> (in base pairs) (Default: 1e6)
                                               #
    norm-method:        "median"               # -- READ Normalization method 
                                               #    <str> [ median | mean | max | value ]
                                               #
    norm-value:         ~                      # -- Normalization value (Float). Ignored if norm-method != "value"
                                               #    <float> (Default: None)
                                               #
    2pow:               False                  # -- Toggle alternate classification threshold
                                               #    <bool> [True|False] (Default: False)
                                               #      - When False: [0.96875,0.90625,0.8125,0.625]
                                               #      - When True : [1-1/(2**4.5), 1-1/(2**3.5), 1-1/(2**2.5), 1-1/(2**1.5)]
                                               #
    add-proxies:        ~                      # -- Include additional 'proxy' individuals from the AADR 1240K dataset
                                               #    within the input PLINK fileset. 
                                               #    <str> [ "Reich" | None (~) ]
                                               #
    maf:                ~                      # -- Minor allele frequency filtration treshold (Float).
                                               #    - Ignored if set to None (~)
                                               #    - Requires caller="pileupCaller" and add-proxies="Reich". 
                                               #    <float> (Default: 0.05)
                                               #
    proxies:            ~                      # -- Specify the sample-ids to fetch from the AADR dataset when
                                               #    adding proxy individuals. Requires caller="pileupCaller" and 
                                               #    add-proxies='Reich'
                                               #    [<str>]
                                               #
  GRUPS-rs:                                    # ---- GRUPS-rs parameters
    pedigree: |-                               # -- Path leading to a predefined template pedigree
      resources/grups-rs/template-pedigrees/siblings-pedigree.ped
    pedigree-pop:     "EUR"                    # -- Pedigree population tag 1000g-phase 3 population tag 
                                               #    <str>
                                               #
    contam-pop:       "EUR"                    # -- Contaminating population tag
                                               #    <str> 
                                               #
    min-depth:        1                        # -- Minimum required local sequencing depth
                                               #    <int> (Default: 1)
                                               #
    mode:             "fst"                    # -- Genotype data format
                                               #    <str> ["fst" | "fst-mmap" | "vcf"] (Default: "fst")
                                               #
    reps:             1000                     # -- Pedigree simulation replicates
                                               #    <int> (Default: 1000)
                                               #
    maf:              0.0                      # -- Minor allele frequency threshold
                                               #    <float> (Default: 0.0)
                                               #
    min-qual:         25                       # -- Minimum Base Quality Threshold
                                               #    <int> (Default: 25)
                                               #
    seq-error-rate:   0.0                      # -- Simulated sequencing error rate. If set to None (~),
                                               #    uses the quality scores found within the input pileup.
                                               #    <float> (Default: 0.0)
                                               #
    self-comparison:  True                     # -- Also estimate kinship by comparing samples to themselves
                                               #    Useful to detect potentially inbred or biased samples
                                               #    <bool> [True | False]
                                               #
    seed:             ~                        # -- RNG seed. Randomly asasigned if set to None (~)
                                               #    <int> (Default: ~)
                                               #
  TKGWV2:                                      # ---- TKGWV2 parameters
    downsample:              True              # -- Apply BAM Downsampling
                                               #    <bool> [True | False]
                                               #
    downsample-N:            57600000          # -- Downsample to N base pairs
                                               #    <int> (Default: 57e6)
                                               #
    downsample-seed:         ~                 # -- Downsampling RNG seed. Randomly assigned if set to None (~)
                                               #    <int> (Default: ~)
                                               #
    target-frequencies: |-                     # -- <path> PLINK Format target frequency (automatically downloaded)
      data/TKGWV2/1240K/1000GP3_EUR_1240K.frq
    min-BQ:                  25                # -- Minimum base quality
                                               #    <int> (Default: 25)
                                               #
    min-MQ:                  25                # -- Minimum mapping quality
                                               #    <int> (Default: 25)
                                               #
    min-depth:               1                 # -- Minimum local sequencing depth
                                               #    <int> (Default: 1)
                                               # 
  KIN:                                         # ---- KIN parameters
    interval:                10000000          #   <int> (Default: 1e7) 
    p0-threshold:            10                #   <int> (Default: 10)
    roh-threshold:           ~                 #         (ignored if None)
    diversity-parameter:     ~                 #         (ignored if None)
    noisy-windows:           ~                 #         (ignored if None)
