# Instructions:
# 
# 1. Add fastq.gz files into a `original-data` directory, at the root of this repository.
#    Directory structure must strictly follow the following nomenclature (see the README for an example)
#    'original-data/samples/{sample-id}/{run-id}/{sample-id}_R{1,2}.fastq.gz'
#
# 2. Add target sample ids within this config file, under the 'samples' tag.
# 3. Specify the name and protocol of each targeted sequencing-run for each sample. 
#    Note that this pipeline can both handle paired-end and single-end sequencing protocols.
samples:
  test-ind1:
    run-00: {protocol: 'paired'}
    run-01: {protocol: 'paired'}
  test-ind2:
    run-00: {protocol: 'paired'}
    run-01: {protocol: 'paired'}
  test-ind3:
    run-00: {protocol: 'paired'}
