- name: --dry-run
  uses: snakemake/snakemake-github-action@v1.25.1
  with:
    directory: '.test'
    snakefile: 'workflow/Snakefile'
    args: '--cores 1 --use-conda --conda-cleanup-pkgs cache --dry-run'
    stagein: "snakemake --version"
    show-disk-usage-on-error: true
