name: --dry-run
on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main ]

jobs: 
  dry-run:
   runs-on: ubuntu-latest
   steps:
     - name: Dry Run
       uses: snakemake/snakemake-github-action@v1.25.1
       with:
        directory: ''
        snakefile: 'workflow/Snakefile'
        args: '--cores 1 --use-conda --conda-cleanup-pkgs cache --dry-run'
        stagein: |
          "snakemake --version"
          "ls -lh"
          "pwd"
        show-disk-usage-on-error: true
